### ISSUE TITLE
Issues building vesktop locally

### ISSUE THREAD

**Issue by dgbogi564** [Vencord/Vesktop#238]
When trying to install pnpm modules in vesktop, I receive this error:
```
$ pnpm i

Lockfile is up to date, resolution step is skipped
Packages: +560
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 0, reused 539, downloaded 0, added 560, done
node_modules/esbuild: Running postinstall script, failed in 40ms
node_modules/esbuild postinstall$ node install.js
│ node:internal/errors:497
│     ErrorCaptureStackTrace(err);
│     ^
│ <ref *1> Error: spawnSync /mnt/sdb2/dev/vesktop/node_modules/esbuild/bin/esbuild EACCES
│     at Object.spawnSync (node:internal/child_process:1124:20)
│     at spawnSync (node:child_process:876:24)
│     at Object.execFileSync (node:child_process:919:15)
│     at validateBinaryVersion (/mnt/sdb2/dev/vesktop/node_modules/esbuild/install.js:98:28)
│     at /mnt/sdb2/dev/vesktop/node_modules/esbuild/install.js:285:5 {
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'spawnSync /mnt/sdb2/dev/vesktop/node_modules/esbuild/bin/esbuild',
│   path: '/mnt/sdb2/dev/vesktop/node_modules/esbuild/bin/esbuild',
│   spawnargs: [ '--version' ],
│   error: [Circular *1],
│   status: null,
│   signal: null,
│   output: null,
│   pid: 0,
│   stdout: null,
│   stderr: null
│ }
│ Node.js v20.8.1
└─ Failed in 40ms at /mnt/sdb2/dev/vesktop/node_modules/esbuild
node_modules/tsx/node_modules/esbuild: Running postinstall script, failed in 36ms
node_modules/tsx/node_modules/esbuild postinstall$ node install.js
│ node:internal/errors:497
│     ErrorCaptureStackTrace(err);
│     ^
│ <ref *1> Error: spawnSync /mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild/bin/esbuild EACCES
│     at Object.spawnSync (node:internal/child_process:1124:20)
│     at spawnSync (node:child_process:876:24)
│     at Object.execFileSync (node:child_process:919:15)
│     at validateBinaryVersion (/mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild/install.js:98:28)
│     at /mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild/install.js:285:5 {
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'spawnSync /mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild/bin/esbuild',
│   path: '/mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild/bin/esbuild',
│   spawnargs: [ '--version' ],
│   error: [Circular *1],
│   status: null,
│   signal: null,
│   output: null,
│   pid: 0,
│   stdout: null,
│   stderr: null
│ }
│ Node.js v20.8.1
└─ Failed in 36ms at /mnt/sdb2/dev/vesktop/node_modules/tsx/node_modules/esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Vendicated** [comment]
google it
