### ISSUE TITLE
Stuck Loading on Arch Linux

### ISSUE THREAD

**Issue by hacktheegg** [Vencord/Vesktop#240]
### Description

Program stuck in the loading phase (before full size window is created)

### Attempts to Fix (in order)

Update, Restart Computer, Uninstall, Clear yay Cache, Reinstall, Restart Computer

### Specs

Software Information:
- **Firmware Version:**                            1.25.0
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.1-arch1-1

**Comment by D3SOX** [comment]
Did you try right-clicking the tray icon and clicking on `Update Vencord` or `Reset Vesktop`? How did you install Vesktop? Can you provide the output when running `vencord-desktop` from the Terminal?

**Comment by hacktheegg** [comment]
tray icon doesn't appear, here is the console log tho:

```[hacktheegg@hacktheegg-ARCH ~]$ vencord-desktop
(node:1459) UnhandledPromiseRejectionWarning: ReferenceError: f is not defined
    at Object.<anonymous> (/home/hacktheegg/.config/VencordDesktop/VencordDesktop/vencordDist/vencordDesktopMain.js:12:5187)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at VCDMain:28:4499
    at VCDMain:1:1022
(Use `vencord-desktop --trace-warnings ...` to show where the warning was created)
(node:1459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)```

**Comment by hacktheegg** [comment]
--trace-warnings results in the following:

```[hacktheegg@hacktheegg-ARCH ~]$ vencord-desktop --trace-warnings
(node:2098) UnhandledPromiseRejectionWarning: ReferenceError: f is not defined
    at Object.<anonymous> (/home/hacktheegg/.config/VencordDesktop/VencordDesktop/vencordDist/vencordDesktopMain.js:12:5187)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at VCDMain:28:4499
    at VCDMain:1:1022
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:2098) ReferenceError: f is not defined
    at Object.<anonymous> (/home/hacktheegg/.config/VencordDesktop/VencordDesktop/vencordDist/vencordDesktopMain.js:12:5187)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at VCDMain:28:4499
    at VCDMain:1:1022

**Comment by hacktheegg** [comment]
i do have [AppIndicator and KStatusNotiferItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) as steam creates one when open

## making it regenerate the config seems to have done it

`yay -Ru vencord-desktop-git` to uninstall
`yay -Sc` to clear cache
`yay -S vencord-desktop-git` to reinstall

**Comment by D3SOX** [comment]
> making it regenerate the config seems to have done it

Ok good to hear

> i do have [AppIndicator and KStatusNotiferItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) as steam creates one when open

Then Vesktop creates the tray icon after whenever your crash occurred. I wasn't aware of that
