### ISSUE TITLE
[windows] Streaming with audio does not work

### ISSUE THREAD

**Issue by NolonQ** [Vencord/Vesktop#334]
**Describe the bug**
streaming with vekstop only works if the "stream with audio" option is disabled

**To Reproduce**
In vesktop start a stream in any quality with the "stream with audio" option enabled

**Expected behavior**
Streaming any quality with audio should work correctly

**Screenshots**
-

**Desktop (please complete the following information):**
 - windows 10 22H2
 - vesktop 0.4.4

**Additional context**
.

**Comment by NolonQ** [comment]
Any input?

**Comment by TheAngryTurkey** [comment]
Same issue here, except for me I can reproduce it if I select the output audio on Windows as my headphones. Any other audio output works and I can stream with audio perfectly fine, but as soon as I select my headphones as the output audio it doesn't let me stream. It doesn't matter what the audio settings are in Vesktop, as soon as I change to audio that isn't the headphones it works fine.
![Vesktop Audio Problem](https://github.com/Vencord/Vesktop/assets/78714461/b8cefc91-698a-491b-b075-ce6dadd64688)

**Comment by thek0d3r** [comment]
Same here two months later...
![image](https://github.com/Vencord/Vesktop/assets/45979391/936a9799-ff4f-45aa-b64c-5efe4c0f0639)

**Comment by Skiexx** [comment]
same problem

**Comment by Vendicated** [comment]
do not reply if you have no new info to contribute. it's spam. react with a :+1:

**Comment by Joshua-Ashton** [comment]
I am getting a similar bug:

It starts with:
`'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()` on the Screenshare dialog

and ends up with

stdout:
```
(node:4830) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:24:2433)
(node:4830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

Console:

```
Error: webpack.findStore found no module
    at Zn (webpack.ts:96:17)
    at Vy (webpack.ts:343:9)
    at webpack.ts:353:28
    at [vencord.lazy.get] (lazy.ts:98:38)
    at Object.get (lazy.ts:120:39)
    at onClick (VCDRenderer:1:15193)
    at Object.eF (67096.30c593c3471420b5c889.js:12:914242)
    at eG (67096.30c593c3471420b5c889.js:12:914396)
    at 67096.30c593c3471420b5c889.js:12:932705
    at re (67096.30c593c3471420b5c889.js:12:932804) Filter: ['MediaEngineStore']
_log @ Logger.ts:35
error @ Logger.ts:53
Zn @ webpack.ts:97
Vy @ webpack.ts:343
(anonymous) @ webpack.ts:353
[vencord.lazy.get] @ lazy.ts:98
get @ lazy.ts:120
onClick @ VCDRenderer:1
eF @ 67096.30c593c3471420b5c889.js:12
eG @ 67096.30c593c3471420b5c889.js:12
(anonymous) @ 67096.30c593c3471420b5c889.js:12
re @ 67096.30c593c3471420b5c889.js:12
rt @ 67096.30c593c3471420b5c889.js:12
(anonymous) @ 67096.30c593c3471420b5c889.js:12
sA @ 67096.30c593c3471420b5c889.js:12
eI @ 67096.30c593c3471420b5c889.js:12
rs @ 67096.30c593c3471420b5c889.js:12
tF @ 67096.30c593c3471420b5c889.js:12
tP @ 67096.30c593c3471420b5c889.js:12
Logger.ts:35  Vencord   VesktopScreenShare  Error while submitting stream. TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Object.get (lazy.ts:120:28)
    at onClick (VCDRenderer:1:15193)
    at Object.eF (67096.30c593c3471420b5c889.js:12:914242)
    at eG (67096.30c593c3471420b5c889.js:12:914396)
    at 67096.30c593c3471420b5c889.js:12:932705
    at re (67096.30c593c3471420b5c889.js:12:932804)
    at rt (67096.30c593c3471420b5c889.js:12:933218)
    at 67096.30c593c3471420b5c889.js:12:938680
    at sA (67096.30c593c3471420b5c889.js:12:995753)
_log @ Logger.ts:35
error @ Logger.ts:53
onClick @ VCDRenderer:1
eF @ 67096.30c593c3471420b5c889.js:12
eG @ 67096.30c593c3471420b5c889.js:12
(anonymous) @ 67096.30c593c3471420b5c889.js:12
re @ 67096.30c593c3471420b5c889.js:12
rt @ 67096.30c593c3471420b5c889.js:12
(anonymous) @ 67096.30c593c3471420b5c889.js:12
sA @ 67096.30c593c3471420b5c889.js:12
eI @ 67096.30c593c3471420b5c889.js:12
rs @ 67096.30c593c3471420b5c889.js:12
tF @ 67096.30c593c3471420b5c889.js:12
tP @ 67096.30c593c3471420b5c889.js:12
758694862408122368:1 Uncaught (in promise) DOMException: Error starting capture
```

**Comment by DustyJinx** [comment]
I've got the same issue as Joshua posted yesterday, but I'm on EndeavourOS (Arch based Linux)
Tried sharing with and without Audio, X11 and Wayland. Does not work.
Trying normal Discord w/o any issues (except w/ Waylad of course but that's Discords shitty part

**Comment by BadKiko** [comment]
yep EndeavourOS after updating get error

```
[3:0620/004346.030868:ERROR:shared_x_display.cc(39)] Unable to open display
'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[2024-06-20 00:43:49.242] [venmic] [info] [patchbay] (get) running venmic 3.4.2
[2024-06-20 00:43:49.394] [venmic] [info] [patchbay] (handle) found default metadata: 40
[2024-06-20 00:43:49.394] [venmic] [info] [patchbay] (meta_update) speaker name: "alsa_output.pci-0000_0c_00.4.iec958-stereo"
(node:3) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at AsyncFunction.<anonymous> (VCDMain:24:2411)
(Use `vesktop.bin --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by Vendicated** [comment]
this is a windows issue. do not hijack it with unrelated Linux issues. they are an issue with your system and have nothing to do with this issue.

**Comment by Different-Name** [comment]
Also experiencing this issue on Windows 10, turning off share with audio allows me to share my screen

**Comment by NekoAlosama** [comment]
Issue persists for me. New info to contribute is version numbers, as the original poster @NolonQ used "windows 10 22H2" and "vesktop 0.4.4".
![image](https://github.com/user-attachments/assets/f999cb7d-82ab-44ed-bc7c-5d44d132f91b)
```
Edition		Windows 11 Pro for Workstations
Version		23H2
Installed on	‎9/‎8/‎2024
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0
```
```
canary 331524 (6970e3a) Build Override: N/A
Vencord 832e874 (Vesktop v1.5.3)
Electron 31.1.0
Chromium 126.0.6478.114
```
There is an `upsteam` label. [Electron has some issues when searching for `DOMException: Could not start audio source`](https://github.com/electron/electron/issues?q=is%3Aissue+%22DOMException%3A+Could+not+start+audio+source%22) and found 2 issues at around the same version claiming that disconnecting their Logitech headsets fixed the issue: [#41697](https://github.com/electron/electron/issues/41697#issuecomment-2058778358) and [#42765](https://github.com/electron/electron/issues/42765#issuecomment-2208602447). Following the closing comment in that second issue just says that it might be an issue with Chrome/Chromium depreciation: [start](https://github.com/electron/electron/issues/42765#issuecomment-2213537807) to [end](https://github.com/electron/electron/issues/41024#issuecomment-1953172032).

Since it seems this is an uncommon issue, it's likely that this problem comes from issues with certain headphone drivers and software. In my situation, I'm using a version of VB-Audio CABLE (specifically, VB-Audio HIFI-CABLE & ASIO-Bridge with ASIO4ALL v2). My setup does not seem to cause problems when screensharing on the Web version of Discord (no Vencord installed).
![Screenshot 2024-09-29 130452](https://github.com/user-attachments/assets/932c9c0a-0187-4dac-834e-57b3710fa7d1)
Replication could be possible by installing one of the VB-Audio CABLEs and choosing to use it as an Output Device in Vesktop.

**Comment by ThaUnknown** [comment]
for any1 looking for a fix, on your default output device [I don't know why this matters] disable "Enable audio enhancements". I GIGA do not know why this matters, as this is recording, not output, but eh... windows.

Steps:
- Win+R
- `mmsys.cpl`
- `Playback` tab
- Find `Default Device`
- RMB -> `Properties`
- `Advanced` tab
- Uncheck `Enable audio enhancements`

<img width="372" height="94" alt="Image" src="https://github.com/user-attachments/assets/da1e731b-0e4e-475b-aa78-19ca63a9e72b" />

**Comment by GeorgePapoulidis** [comment]
Seems like the solution by @ThaUnknown works, but the guide is incorrect at least on W11. You can find the option through the Settings->System->Sound->*Pick your device*->Advanced Settings-> Turn it off. 

Seems like turning off the enchancements only for the device that I use on Vesktop seems to do the trick, without needing to touch the rest

**Comment by Vendicated** [comment]
Will be fixed in v1.6.8
