### ISSUE TITLE
Component failed to load when showing bios/profile description/about me

### ISSUE THREAD

**Issue by Whitesudev** [Vencord/Vesktop#511]
VM827 react_devtools_backend.js:4026  Vencord   Webpack  Error: webpack.findByCode found no module
    at Jn (webpack.ts:96:17)
    at i1 (webpack.ts:324:9)
    at webpack.ts:334:28
    at [vencord.lazy.get] (lazy.ts:98:38)
    at Wa.<computed> [as apply] (lazy.ts:56:65)
    at index.tsx:78:47
    at aS (44076.b5f9426088ebaff2b53a.js:12:899964)
    at u (44076.b5f9426088ebaff2b53a.js:12:955175)
    at sB (44076.b5f9426088ebaff2b53a.js:12:938190)
    at 44076.b5f9426088ebaff2b53a.js:12:938056 Filter: [',"--profile-gradient-primary-color"']
overrideMethod @ VM827 react_devtools_backend.js:4026
_log @ Logger.ts:35
error @ Logger.ts:53
Jn @ webpack.ts:97
i1 @ webpack.ts:324
(anonymous) @ webpack.ts:334
[vencord.lazy.get] @ lazy.ts:98
Wa.<computed> @ lazy.ts:56
(anonymous) @ index.tsx:78
aS @ 44076.b5f9426088ebaff2b53a.js:12
u @ 44076.b5f9426088ebaff2b53a.js:12
sB @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sF @ 44076.b5f9426088ebaff2b53a.js:12
sM @ 44076.b5f9426088ebaff2b53a.js:12
r6 @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
VM827 react_devtools_backend.js:4026 Lazy factory failed: ()=>i1(...e)
overrideMethod @ VM827 react_devtools_backend.js:4026
[vencord.lazy.get] @ lazy.ts:100
Wa.<computed> @ lazy.ts:56
(anonymous) @ index.tsx:78
aS @ 44076.b5f9426088ebaff2b53a.js:12
u @ 44076.b5f9426088ebaff2b53a.js:12
sB @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sF @ 44076.b5f9426088ebaff2b53a.js:12
sM @ 44076.b5f9426088ebaff2b53a.js:12
r6 @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
VM827 react_devtools_backend.js:4026 TypeError: Function.prototype.apply was called on null, which is null and not a function
    at Wa.<computed> [as apply] (lazy.ts:56:50)
    at index.tsx:78:47
    at aS (44076.b5f9426088ebaff2b53a.js:12:899964)
    at u (44076.b5f9426088ebaff2b53a.js:12:955175)
    at sB (44076.b5f9426088ebaff2b53a.js:12:938190)
    at 44076.b5f9426088ebaff2b53a.js:12:938056
    at sF (44076.b5f9426088ebaff2b53a.js:12:938064)
    at sC (44076.b5f9426088ebaff2b53a.js:12:934815)
    at sM (44076.b5f9426088ebaff2b53a.js:12:935204)
    at r6 (44076.b5f9426088ebaff2b53a.js:12:883839)
overrideMethod @ VM827 react_devtools_backend.js:4026
oe @ 44076.b5f9426088ebaff2b53a.js:12
a.componentDidCatch.n.callback @ 44076.b5f9426088ebaff2b53a.js:12
iW @ 44076.b5f9426088ebaff2b53a.js:12
oX @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sY @ 44076.b5f9426088ebaff2b53a.js:12
sM @ 44076.b5f9426088ebaff2b53a.js:12
r6 @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
VM827 react_devtools_backend.js:4026  Vencord   React ErrorBoundary  A component threw an Error
 TypeError: Function.prototype.apply was called on null, which is null and not a function
    at Wa.<computed> [as apply] (lazy.ts:56:50)
    at index.tsx:78:47
    at aS (44076.b5f9426088ebaff2b53a.js:12:899964)
    at u (44076.b5f9426088ebaff2b53a.js:12:955175)
    at sB (44076.b5f9426088ebaff2b53a.js:12:938190)
    at 44076.b5f9426088ebaff2b53a.js:12:938056
    at sF (44076.b5f9426088ebaff2b53a.js:12:938064)
    at sC (44076.b5f9426088ebaff2b53a.js:12:934815)
    at sM (44076.b5f9426088ebaff2b53a.js:12:935204)
    at r6 (44076.b5f9426088ebaff2b53a.js:12:883839)
overrideMethod @ VM827 react_devtools_backend.js:4026
_log @ Logger.ts:35
error @ Logger.ts:53
componentDidCatch @ ErrorBoundary.tsx:73
a.componentDidCatch.n.callback @ 44076.b5f9426088ebaff2b53a.js:12
iW @ 44076.b5f9426088ebaff2b53a.js:12
oX @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sY @ 44076.b5f9426088ebaff2b53a.js:12
sM @ 44076.b5f9426088ebaff2b53a.js:12
r6 @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
VM827 react_devtools_backend.js:4026  Vencord   React ErrorBoundary  Component Stack 
    at VencordRenderer:179:4892
    at <anonymous> (VencordRenderer:14:12866)
    at r
    at N (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:3207963)
    at div
    at https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:7247571
    at s (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:524083)
    at H (WebpackModule192133:2:663)
    at div
    at T.Overlay (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5425480)
    at u (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5426010)
    at div
    at div
    at T (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5424246)
    at N (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:3207963)
    at s (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:524083)
    at div
    at https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:498899
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:395925)
    at l (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5373622)
    at d (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:2567844)
    at H (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5447779)
    at https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5452502
    at o (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5411821)
    at div
    at I (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:610160)
    at N (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:3207963)
    at div
    at T (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:706879)
    at R (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:547070)
    at A (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:539701)
    at s (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:524083)
    at O (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:603641)
    at I (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:607994)
    at b (https://discord.com/assets/d686609e3e183fe8ebb2.js:1:10100)
    at N (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:3207963)
    at div
    at https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:7250030
    at div
    at d (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:2567844)
    at F (https://discord.com/assets/d686609e3e183fe8ebb2.js:1:12684)
    at div
    at div
    at e3 (WebpackModule823748:2:9770)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:678004)
    at https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:457458
    at eval (WebpackModule823748:2:17253)
    at eR (WebpackModule176299:2:2336)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1002477)
    at o (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:2571729)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1003175)
    at div
    at div
    at div
    at eV (WebpackModule176299:2:7332)
    at div
    at u (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:1:288933)
    at D (WebpackModule718813:2:4387)
    at div
    at o (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:7690720)
    at b (WebpackModule718813:2:4656)
    at U (WebpackModule718813:2:5645)
    at div
    at d (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:652647)
    at https://discord.com/assets/6d826444397e9ac6f233.js:1:211439
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1002477)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1003175)
    at ti (https://discord.com/assets/6d826444397e9ac6f233.js:1:58658)
    at Suspense
    at _
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1002477)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:1003175)
    at div
    at f (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:539220)
    at VerificationLayerProvider
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:3346039)
    at u (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:3344749)
    at div
    at div
    at f (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:539220)
    at AppLayerProvider
    at T (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:2420384)
    at N (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:3207963)
    at D (WebpackModule628123:2:2564)
    at c (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:3393082)
    at E (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:3393537)
    at c (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:7300990)
    at l (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:526068)
    at I (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:2437811)
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:705749)
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5274645)
    at t.default (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:3387180)
    at Z (https://discord.com/assets/web.2c8369fe19ff3515c0ba.js:1:6038)
    at https://discord.com/assets/web.2c8369fe19ff3515c0ba.js:1:11308
    at c (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:7300144)
    at https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:789801
    at l (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:783973)
    at c (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:503301)
    at App
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:999741)
    at t (https://discord.com/assets/44076.b5f9426088ebaff2b53a.js:12:976805)
    at f (https://discord.com/assets/web.2c8369fe19ff3515c0ba.js:1:35067)
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:705749)
    at _ (https://discord.com/assets/73050.6f070fcba40a9414f9f6.js:1:5274645)
overrideMethod @ VM827 react_devtools_backend.js:4026
_log @ Logger.ts:35
error @ Logger.ts:53
componentDidCatch @ ErrorBoundary.tsx:74
a.componentDidCatch.n.callback @ 44076.b5f9426088ebaff2b53a.js:12
iW @ 44076.b5f9426088ebaff2b53a.js:12
oX @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
e @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sY @ 44076.b5f9426088ebaff2b53a.js:12
sM @ 44076.b5f9426088ebaff2b53a.js:12
r6 @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
VM827 react_devtools_backend.js:4026 [ComponentDispatchUtils] ComponentDispatch.subscribe: Attempting to add a duplicate listener POPOUT_CLOSE

**Comment by Whitesudev** [comment]
![vvHsiuX](https://github.com/Vencord/Vesktop/assets/98481741/5242b411-63e2-46e7-a14a-29ae2dd5ec15)
