### ISSUE TITLE
[Bug] Vesktop fails to launch

### ISSUE THREAD

**Issue by ISSOtm** [Vencord/Vesktop#675]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Sway

### What happens when the bug or crash occurs?

Launching the application passes the "Loading Vesktop" foxgirl (:3), and then stays on a blank window.

Dev tools' console reports the following:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'can')
    at Object.isHiddenChannel (index.tsx:485:33)
    at Object.resolveGuildChannels (index.tsx:501:61)
    at q.getChannels (WebpackModule984933:2:2732)
    at q.getFirstChannelOfType (WebpackModule984933:2:2885)
    at q.getFirstChannel (WebpackModule984933:2:3052)
    at q.getDefaultChannel (WebpackModule984933:2:3308)
    at x (25624.cfab532100605014a013.js:1:5951353)
    at j.getChannelId (25624.cfab532100605014a013.js:1:5953262)
    at 306680 (25624.cfab532100605014a013.js:1:5901737)
    at e.<computed> (patchWebpack.ts:197:17)
```

It's unclear if this is caused by a plugin (of note is a few "patch had no effect" warnings a little above). I'm not sure how to disable them outside of the GUI that is not launching... ><

Edit: I forgot to mention, but the bug did not happen until today. I restarted Vesktop normally after applying the last update a few days ago, so I'm not sure what changed.

### What is the expected behaviour?

Vesktop launching as usual.

### How do you recreate this bug or crash?

1. Launch Vesktop
2. Easy reproducer, for once!

### Debug Logs

```
[97557:0619/193204.982694:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[97557:0619/193204.992890:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[97557:0619/193207.823066:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[97516:0619/193213.054639:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

I get these from the AppImage, but not the AUR package. The issue reproduces on both, though.

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
#669

**Comment by ISSOtm** [comment]
Ah, I didn't check in the closed issues. My bad. Thank you for your time!

**Comment by ISSOtm** [comment]
Unfortunately, the fix presented over there (I do not have a tray, so pasting `Vencord.Updater.update()`) does not fix the issue.

I get a `Promise` object, and `await`ing that just returns `true`, but restarting Vesktop (again, no tray, so AFAICT no persisting processes) still yields the same. :sweat_smile:

**Comment by ISSOtm** [comment]
I fixed it by running `Vesktop.Settings.store.tray = true` in the DevTools Console, which immediately enables the tray. Then that can be right-clicked to "Update Vesktop", which *did* work!

cc @Vendicated if you want to add that to #669's post.

Thank you very much for working on this! ^^

**Comment by Wartori54** [comment]
Same happened to me, where `Vencord.Update.update()` just returned `true` instantly, but after manually running `Vencord.Update.checkForUpdates()` and then re-running `Vencord.Update.update()` it actually updated to latest and fixed itself.

All of this using `vesktop-bin` from the arch user repositories.
