### ISSUE TITLE
[Bug] Gray Screen upon Launching Vesktop

### ISSUE THREAD

**Issue by SkuxSaint** [Vencord/Vesktop#932]
### Discord Account

skuxsaint

### Operating System

Windows 11

### Package Type

Windows 11 Installer

### What happens when the bug or crash occurs?

Gray Screen Occurs when launching the Vesktop App , Ive restarted - reinstalled - used `await Vencord.Updater.checkForUpdates()
await Vencord.Updater.update()
VesktopNative.app.relaunch()` and `Vesktop.Settings.store.discordBranch = "stable"` from previous Issues ive seen and wont work.
![Screenshot 2024-10-27 131033](https://github.com/user-attachments/assets/b143cf1e-4866-4536-9ab5-a2cb2a2f5c2b)

### What is the expected behaviour?

I expect for Vesktop to not be on a Gray Screen when opening the app

### How do you recreate this bug or crash?

1 . Open Vesktop 
2 . Gray Screen

### Debug Logs

```
Uncaught Error: Sentry successfully disabled
    at Function.set (noTrack.ts:118:23)
    at assets/sentry.05d17ce4b4160ad7a17b.js:453:37896
    at assets/sentry.05d17ce4b4160ad7a17b.js:453:38435
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
6378a54189f0f743e0a7.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
3a8c2a18b4d521d8d69b.js:1 
        
        
       Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
web.96b4cfe2a5e310ec042c.js:12 
        
        
       GET https://discord.com/assets/3a8c2a18b4d521d8d69b.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)
n.l @ web.96b4cfe2a5e310ec042c.js:12
n.f.j @ web.96b4cfe2a5e310ec042c.js:12
(anonymous) @ web.96b4cfe2a5e310ec042c.js:12
n.e @ web.96b4cfe2a5e310ec042c.js:12
createPromise @ web.96b4cfe2a5e310ec042c.js:12
u @ web.96b4cfe2a5e310ec042c.js:12
web.96b4cfe2a5e310ec042c.js:12 
        
        
       GET https://discord.com/assets/6378a54189f0f743e0a7.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)
n.l @ web.96b4cfe2a5e310ec042c.js:12
n.f.j @ web.96b4cfe2a5e310ec042c.js:12
(anonymous) @ web.96b4cfe2a5e310ec042c.js:12
n.e @ web.96b4cfe2a5e310ec042c.js:12
createPromise @ web.96b4cfe2a5e310ec042c.js:12
u @ web.96b4cfe2a5e310ec042c.js:12
2web.96b4cfe2a5e310ec042c.js:12 ChunkLoadError
    at n.f.j (web.96b4cfe2a5e310ec042c.js:12:13409102)
    at web.96b4cfe2a5e310ec042c.js:12:13365240
    at Array.reduce (<anonymous>)
    at n.e (web.96b4cfe2a5e310ec042c.js:12:13365206)
    at createPromise (web.96b4cfe2a5e310ec042c.js:12:2732626)
    at u (web.96b4cfe2a5e310ec042c.js:12:9170158)
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
Optional: Back up your Vencord settings

1. Uninstall Vesktop
2. Delete `%APPDATA%/Vesktop` and `%LOCALAPPDATA%/Vesktop`
3. Install Vesktop 

If it's fixed, good

Otherwise, it's an issue with your network. In this case, try:
- restarting / resetting your router
- changing your dns resolver to [1.1.1.1](https://developers.cloudflare.com/1.1.1.1/setup/) or [8.8.8.8](https://developers.google.com/speed/public-dns/docs/using)
- using a [VPN](https://mullvad.net/en)
