### ISSUE TITLE
[Bug] White screen on start, requires to relaunch Vesktop

### ISSUE THREAD

**Issue by Kodarru** [Vencord/Vesktop#969]
### Discord Account

kodarru

### Operating System

Linux

### Linux Only ~ Desktop Environment

Hyprland on Wayland 

### Package Type

Flatpak

### What happens when the bug or crash occurs?

The bug seems to only happen when starting Linux and opening Vesktop. As far as I know, it does not happen if Linux has been running for a bit. There will be no splash screen or anything. It would immediately open to a white screen.

![image](https://github.com/user-attachments/assets/0df5b16e-f370-49e6-bc01-6d0e65d56548)
![image](https://github.com/user-attachments/assets/2e68dd59-0f34-47cd-b38f-c7265312ec10)
![image](https://github.com/user-attachments/assets/3fe4efe3-a3b3-40e3-a840-ad97f2e779a4)

And no, it's not because of the no internet icon. Internet is working completely fine. It's been a bug with my rice I need to fix. 

 

### What is the expected behaviour?

Should load normally and lead to the main Discord/Splash screen

### How do you recreate this bug or crash?

1. Boot Arch Linux 
2. Immediately open Vesktop

I really don't know how to give steps on how to recreate the bug

### Debug Logs

```
ncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at VencordDesktopRenderer:16:3440
    at VencordDesktopRenderer:5:497
    at VencordDesktopRenderer:16:50195
    at VencordDesktopRenderer:5:497
    at VencordDesktopRenderer:25:6824
    at VencordDesktopRenderer:5:497
    at VencordDesktopRenderer:25:7117
    at VencordDesktopRenderer:5:497
    at VencordDesktopRenderer:249:43291
    at VencordDesktopRenderer:5:497
VCDRenderer:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at VCDRenderer:1:1144
    at VCDRenderer:1:26074
VCDPreload:1 Uncaught (in promise) Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at Object.<anonymous> (VCDPreload:1:1903)
    at Object.<anonymous> (VCDPreload:5:3)
    at Module._compile (VM54 loader:1373:14)
    at Module._extensions..js (VM54 loader:1432:10)
    at Module.load (VM54 loader:1215:32)
    at Module._load (VM54 loader:1031:12)
    at c._load (VM68 node_init:2:17025)
    at s._load (VM110 renderer_init:2:31018)
    at VM110 renderer_init:2:33087
    at VM110 renderer_init:2:33556
VCDPreload:1 Uncaught (in promise) Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at Object.<anonymous> (VCDPreload:1:1986)
    at Object.<anonymous> (VCDPreload:5:3)
    at Module._compile (VM54 loader:1373:14)
    at Module._extensions..js (VM54 loader:1432:10)
    at Module.load (VM54 loader:1215:32)
    at Module._load (VM54 loader:1031:12)
    at c._load (VM68 node_init:2:17025)
    at s._load (VM110 renderer_init:2:31018)
    at VM110 renderer_init:2:33087
    at VM110 renderer_init:2:33556
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Kodarru** [comment]
A restart from the taskbar icon will fix the issue

**Comment by Sebron** [comment]
Discord Account
Sebron

Operating System
Garuda (Arch Linux)

Linux Only ~ Desktop Environment
KDE 6.8.0, Plasma 6.2.3, Wayland

Package Type
distro package install

What happens when the bug or crash occurs?
On system startup Vesktop launches to a white screen, a relaunch from taskbar resolves the issue.

**Comment by Kodarru** [comment]
??

**Comment by Sebron** [comment]
why was my comment marked as spam? I'm just trying to indicate that this issue also occurs on my setup. The common factor between the two being Wayland. I haven't tried running an X11 session to see if there is a difference tho.

**Comment by Kodarru** [comment]
I don't mark it as spam. GitHub does.

**Comment by Sebron** [comment]
hence the confussion...

**Comment by Kodarru** [comment]
No?? I was confused on why you said it 🤦‍♀️ you didn't say anything about "happening on my system" you just posted your system information.

**Comment by 8Vinso8** [comment]
Using vesktop from AUR on Arch with Hyprland. Same issue. But disabling tray icon somehow fixes it

**Comment by aaprispeshkin** [comment]
Same issue here, happens while using all vesktop versions (flatpak, source, appimage and aur). Dev tools output same mistakes outlined here, however nothing seems to fix it. Running from the terminal results in these logs:
```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
(node:26838) electron: Failed to load URL: https://discord.com/app with error: ERR_TIMED_OUT
(Use `electron --trace-warnings ...` to show where the warning was created)
```

**Comment by henlo-birb** [comment]
this could be caused by your network settings being messed up, preventing the discord webpage from loading.  I was having this issue and it turned out to be because my proxy settings were broken

**Comment by Kodarru** [comment]
My network settings were completely fine.

**Comment by slxdy** [comment]
For me, this happens when trying to launch Vesktop without an internet connection. 
Also, don't restart the entire process. A simple CTRL+R works too

**Comment by aaprispeshkin** [comment]
> For me, this happens when trying to launch Vesktop without an internet connection. Also, don't restart the entire process. A simple CTRL+R works too

Nope, unfortunately this still happens if I launch vesktop separately after my system has already booted and internet connection was established. CTRL+R also doesn't help, neither does "Restart" button in tray (if that matters at all, "Repair Vencord" button also doesn't help)

**Comment by xii69** [comment]
Same issue, Arch Linux with Hyprland, Vencord is just a white screen

**Comment by Kodarru** [comment]
If you're going to add onto this thread, please also try to post logs. Press CTRL+SHIFT+i on the white screen, then click console and take a screenshot of that. Thank you!

**Comment by aaprispeshkin** [comment]
![image](https://github.com/user-attachments/assets/93417f55-05c8-4b66-a289-45653c16e023)
Funnily enough, i went to double-check the logs to make sure the issue still persists, but this time they are different, no longer throwing the "Uncaught DOMException", as outlined in the original post on this issue. Anyway here they are, hope this helps somehow
```
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at VencordDesktopRenderer:5:497
    at Settings.ts:21:1
    at VencordDesktopRenderer:5:497
    at ContributorModal.tsx:9:1
    at VencordDesktopRenderer:5:497
    at index.tsx:26:1
    at VencordDesktopRenderer:5:497
    at import-plugins:~plugins:1:1
    at VencordDesktopRenderer:5:497
    at Badges.ts:22:1
VCDRenderer:1 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at VCDRenderer:1:26609
VCDPreload:1 Uncaught (in promise) Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at Object.<anonymous> (VCDPreload:1:1903)
    at Object.<anonymous> (VCDPreload:5:3)
    at Module._compile (VM55 loader:1484:14)
    at Module._extensions..js (VM55 loader:1564:10)
    at Module.load (VM55 loader:1295:32)
    at Module._load (VM55 loader:1111:12)
    at c._load (VM68 node_init:2:16955)
    at s._load (VM111 renderer_init:2:30981)
    at VM111 renderer_init:2:33050
    at VM111 renderer_init:2:33519
VCDPreload:1 Uncaught (in promise) Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at Object.<anonymous> (VCDPreload:1:1986)
    at Object.<anonymous> (VCDPreload:5:3)
    at Module._compile (VM55 loader:1484:14)
    at Module._extensions..js (VM55 loader:1564:10)
    at Module.load (VM55 loader:1295:32)
    at Module._load (VM55 loader:1111:12)
    at c._load (VM68 node_init:2:16955)
    at s._load (VM111 renderer_init:2:30981)
    at VM111 renderer_init:2:33050
    at VM111 renderer_init:2:33519
    ```

**Comment by WarpspeedSCP** [comment]
happened to a friend of mine on current latest bazzite, from the discover package manager
